/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import DAO.UserDAO;
import DTO.ProductDTO;
import java.awt.CardLayout;
import UI.*;
import DTO.UserDTO;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.time.LocalDateTime;
import javax.swing.JOptionPane;


/**
 *
 * @author ACER
 */
public class Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard.class.getName());
    CardLayout layout;
    String userSelect;
    String username;
    UserDTO userDTO;
    LocalDateTime outTime;
    /**
     * Creates new form dash
     * @param username
     * @param userType
     * @param userDTO
     */
    public Dashboard(String username,String userType,UserDTO userDTO) {
        initComponents();
        menuPanel.setVisible(true);
        navPanel.setVisible(false);
        this.username=username;
        this.userDTO = userDTO;
        userSelect=userType;
        layout = new CardLayout();
        
        
        if("EMPLOYEE".equalsIgnoreCase(userDTO.getUserType())){
            userBtn.setVisible(false);
            logsBtn.setVisible(false);   
        }
        currentUserSession();
        
        displayPanel.setLayout(layout);
        displayPanel.add("Home", new HomePage(username)); //ass a panel(card) of name Home to the displayPanel
        displayPanel.add("Product", new ProductPage());
        displayPanel.add("CurrentStocks", new StocksPage());
        displayPanel.add("User", new Userpage());
        displayPanel.add("Userlogs", new UserLogs());
        displayPanel.add("PurchasePage", new PurchasePage(this));
        displayPanel.add("SupplierPage", new SupplierPage());
        displayPanel.add("SalesPage", new SalesPage(username,this));

        mainPanel.setLayout(null);

        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                outTime = LocalDateTime.now();
                userDTO.setOutTime(String.valueOf(outTime));
                userDTO.setUsername(username);
                new UserDAO().addUserLogin(userDTO);
                super.windowClosing(e);
            }
        });
        
        //layout.show(displayPanel, "Home");

    }
    public void addSupplPage(){
             layout.show(displayPanel, "SupplierPage");
    }
    
    /*public void addProductpage(){
        layout.show(displayPanel, "ProductPage"); //Show me the card I registered earlier as Home.
    }*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        menuBtn = new javax.swing.JButton();
        navPanel = new javax.swing.JPanel();
        homebtn = new javax.swing.JButton();
        prodBtn = new javax.swing.JButton();
        stocksBtn = new javax.swing.JButton();
        purchaseBtn = new javax.swing.JButton();
        suppBtn = new javax.swing.JButton();
        salesBtn = new javax.swing.JButton();
        userBtn = new javax.swing.JButton();
        logsBtn = new javax.swing.JButton();
        displayPanel = new javax.swing.JPanel();
        logoutbtn = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mainPanel.setBackground(new java.awt.Color(51, 51, 51));
        mainPanel.setLayout(null);

        menuPanel.setBackground(new java.awt.Color(51, 51, 51));
        menuPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        menuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        menuBtn.setBackground(new java.awt.Color(102, 102, 102));
        menuBtn.setText("MENU");
        menuBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        menuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBtnActionPerformed(evt);
            }
        });
        menuPanel.add(menuBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 15, 81, -1));

        mainPanel.add(menuPanel);
        menuPanel.setBounds(1, 0, 110, 50);

        navPanel.setBackground(new java.awt.Color(51, 51, 51));
        navPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        homebtn.setBackground(new java.awt.Color(102, 102, 102));
        homebtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Documents\\NetBeansProjects\\InventoryManagementSys\\lib\\icons\\homepages_home_house_icon_150665.png")); // NOI18N
        homebtn.setActionCommand("\n");
        homebtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homebtnActionPerformed(evt);
            }
        });

        prodBtn.setBackground(new java.awt.Color(102, 102, 102));
        prodBtn.setText("Product");
        prodBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        prodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodBtnActionPerformed(evt);
            }
        });

        stocksBtn.setBackground(new java.awt.Color(102, 102, 102));
        stocksBtn.setText("Stocks");
        stocksBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        stocksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stocksBtnActionPerformed(evt);
            }
        });

        purchaseBtn.setBackground(new java.awt.Color(102, 102, 102));
        purchaseBtn.setText("Purchase");
        purchaseBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        purchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseBtnActionPerformed(evt);
            }
        });

        suppBtn.setBackground(new java.awt.Color(102, 102, 102));
        suppBtn.setText("Supplier");
        suppBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        suppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppBtnActionPerformed(evt);
            }
        });

        salesBtn.setBackground(new java.awt.Color(102, 102, 102));
        salesBtn.setText("Sales");
        salesBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        salesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesBtnActionPerformed(evt);
            }
        });

        userBtn.setBackground(new java.awt.Color(102, 102, 102));
        userBtn.setText("User");
        userBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });

        logsBtn.setBackground(new java.awt.Color(102, 102, 102));
        logsBtn.setText("User Logs");
        logsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        logsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navPanelLayout.createSequentialGroup()
                        .addComponent(logsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navPanelLayout.createSequentialGroup()
                        .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(userBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(suppBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(prodBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(stocksBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(purchaseBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(salesBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(16, 16, 16))))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(homebtn)
                .addGap(38, 38, 38)
                .addComponent(prodBtn)
                .addGap(48, 48, 48)
                .addComponent(stocksBtn)
                .addGap(48, 48, 48)
                .addComponent(suppBtn)
                .addGap(48, 48, 48)
                .addComponent(salesBtn)
                .addGap(48, 48, 48)
                .addComponent(purchaseBtn)
                .addGap(48, 48, 48)
                .addComponent(userBtn)
                .addGap(48, 48, 48)
                .addComponent(logsBtn)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        mainPanel.add(navPanel);
        navPanel.setBounds(0, 50, 110, 570);

        displayPanel.setBackground(new java.awt.Color(51, 51, 51));
        displayPanel.setLayout(new java.awt.CardLayout());
        mainPanel.add(displayPanel);
        displayPanel.setBounds(110, 50, 760, 570);

        logoutbtn.setBackground(new java.awt.Color(153, 153, 153));
        logoutbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Documents\\NetBeansProjects\\InventoryManagementSys\\lib\\icons\\log-out_icon-icons.com_50106.png")); // NOI18N
        logoutbtn.setText("LOGOUT");
        logoutbtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        mainPanel.add(logoutbtn);
        logoutbtn.setBounds(750, 10, 120, 30);

        nameLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Documents\\NetBeansProjects\\InventoryManagementSys\\lib\\icons\\user_icon_150670.png")); // NOI18N
        nameLabel.setText("USER:");
        mainPanel.add(nameLabel);
        nameLabel.setBounds(560, 10, 180, 30);

        getContentPane().add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
   
    private void menuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBtnActionPerformed
        // TODO add your handling code here:
        navPanel.setVisible(!navPanel.isVisible());                                         
    }//GEN-LAST:event_menuBtnActionPerformed

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        layout.show(displayPanel, "User");
    }//GEN-LAST:event_userBtnActionPerformed

    private void homebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homebtnActionPerformed
        // TODO add your handling code here:
        layout.show(displayPanel, "Home");
    }//GEN-LAST:event_homebtnActionPerformed

    private void prodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodBtnActionPerformed
        // TODO add your handling code here:
        layout.show(displayPanel, "Product");
    }//GEN-LAST:event_prodBtnActionPerformed

    private void logsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logsBtnActionPerformed
        layout.show(displayPanel, "Userlogs");
    }//GEN-LAST:event_logsBtnActionPerformed

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
        int opt = JOptionPane.showConfirmDialog(
                null,
                "<html>Are you sure you want to logout?<br>You will have to login again.<html>",
                "Confirmation",
                JOptionPane.YES_NO_OPTION);
        if (opt==JOptionPane.YES_OPTION){
            outTime = LocalDateTime.now();
            userDTO.setOutTime(String.valueOf(outTime));
            userDTO.setUsername(username);
            new UserDAO().addUserLogin(userDTO);
            dispose();
            LoginPage logPage = new LoginPage();
            logPage.setVisible(true);
        }
    }//GEN-LAST:event_logoutbtnActionPerformed

    private void stocksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stocksBtnActionPerformed
        layout.show(displayPanel,"CurrentStocks");
    }//GEN-LAST:event_stocksBtnActionPerformed

    private void purchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_purchaseBtnActionPerformed
        layout.show(displayPanel, "PurchasePage");
    }//GEN-LAST:event_purchaseBtnActionPerformed

    private void suppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppBtnActionPerformed
        addSupplPage();
    }//GEN-LAST:event_suppBtnActionPerformed

    private void salesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesBtnActionPerformed
        layout.show(displayPanel, "SalesPage");

    }//GEN-LAST:event_salesBtnActionPerformed
    // Method to display the user currently logged in
    public void currentUserSession() {
        UserDTO userDTO = new UserDTO();
        new UserDAO().getFullName(userDTO, username);
        nameLabel.setText("User: " + userDTO.getFullName() + " ("+userSelect+")");
    }
   
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayPanel;
    private javax.swing.JButton homebtn;
    private javax.swing.JButton logoutbtn;
    private javax.swing.JButton logsBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton menuBtn;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel navPanel;
    private javax.swing.JButton prodBtn;
    private javax.swing.JButton purchaseBtn;
    private javax.swing.JButton salesBtn;
    private javax.swing.JButton stocksBtn;
    private javax.swing.JButton suppBtn;
    private javax.swing.JButton userBtn;
    // End of variables declaration//GEN-END:variables
}
